# Generated by Django 3.1 on 2020-08-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=128, verbose_name='Ник')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=128, verbose_name='Почта')),
                ('website', models.CharField(max_length=128, verbose_name='Сайт')),
                ('company', models.TextField(verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название статьи')),
                ('body', models.TextField(verbose_name='Текст статьи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
